fix: Skip deploy jobs if there's missing credentials

diff --git a/.github/workflows/chromatic.yml b/.github/workflows/chromatic.yml
--- a/.github/workflows/chromatic.yml
+++ b/.github/workflows/chromatic.yml
@@ -7,15 +7,28 @@ on: push
 # List of jobs
 jobs:
   test:
-    # Operating System
+    name: 'Chromatic Deployment'
     runs-on: ubuntu-latest
-    # Job steps
     steps:
-      - uses: actions/checkout@v1
-      - run: yarn
-        #👇 Adds Chromatic as a step in the workflow
+      - name: 'Check out Git repository'
+        uses: actions/checkout@v1
+
+      - name: 'Check secrets'
+        id: check-secrets
+        run: echo "::set-output name=has-secrets::$([ -n "${{ env.CHROMATIC_PROJECT_TOKEN }}" ] && echo true || echo false)"
+        env:
+          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+
+      - name: 'Warn required secrets'
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'false' }}
+        run: echo 'CHROMATIC_PROJECT_TOKEN missing in Github secrets. Skipping Storybook deployment.'
+
+      - name: 'Install dependencies'
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
+        run: yarn
+
       - uses: chromaui/action@v1
-        # Options required for Chromatic's GitHub Action
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         with:
           #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
diff --git a/.github/workflows/eas.yml b/.github/workflows/eas.yml
--- a/.github/workflows/eas.yml
+++ b/.github/workflows/eas.yml
@@ -13,13 +13,25 @@ jobs:
       - name: Check out Git repository
         uses: actions/checkout@v2
 
+      - name: 'Check secrets'
+        id: check-secrets
+        run: echo "::set-output name=has-secrets::$([ -n "${{ env.EXPO_ACCESS_TOKEN }}" ] && echo true || echo false)"
+        env:
+          EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
+
+      - name: 'Warn required secrets'
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'false' }}
+        run: echo 'EXPO_ACCESS_TOKEN missing in Github secrets. Skipping Storybook deployment.'
+
       - name: Setup Node
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         uses: actions/setup-node@v2
         with:
           node-version: 16.x
           cache: yarn
 
       - name: Setup Expo
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         uses: expo/expo-github-action@v7
         with:
           expo-version: latest
@@ -30,9 +42,11 @@ jobs:
 
       - name: Find yarn cache
         id: yarn-cache-path
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         run: echo "::set-output name=dir::$(yarn cache dir)"
 
       - name: Restore cache
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-path.outputs.dir }}
@@ -40,9 +54,11 @@ jobs:
           restore-keys: ${{ runner.os }}-yarn-
 
       - name: Install Node.js dependencies
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         run: yarn install --immutable
 
       - name: Deploy with EAS update
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         run: cd apps/expo && eas update --auto
         env:
           ENV: staging
@@ -50,6 +66,7 @@ jobs:
 
       # -i- Optional for demo purposes, feel free to remove this last step -i-
       - name: Deploy with Expo publish
+        if: ${{ steps.check-secrets.outputs.has-secrets == 'true' }}
         run: cd apps/expo && EXPO_PUBLISH=true yarn expo publish --release-channel=starter-preview-main
         env:
           ENV: staging
